
SELECT * FROM SB1990

SELECT * FROM SBM990 AS SBM
WHERE SBM.BM_DESC = 'PELÍCULAS'

SELECT DISTINCT B1_DESC, B1_GRUPO, BM_GRUPO  FROM SB1990 AS SB1
INNER JOIN SBM990 AS SBM
ON SB1.B1_GRUPO = SBM.BM_GRUPO
AND SB1.D_E_L_E_T_ = '' AND SBM.D_E_L_E_T_ = ''
WHERE SBM.BM_DESC = 'PELÍCULAS'
